version: 2.1
orbs:
  ruby: circleci/ruby@0.2.1

jobs:
  "rubocop":
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - ruby/load-cache
      - ruby/install-deps
      - run:
          name: Update bundler
          command: gem update bundler
      - run:
          name: Run Rubocop
          command: bundle exec rubocop
      - ruby/save-cache
  "rspec":
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - ruby/load-cache
      - ruby/install-deps
      - run:
          name: Update bundler
          command: gem update bundler
      - ruby/run-tests
      - ruby/save-cache
workflows:
  version: 2
  rubocop-rspec:
    jobs:
      - rubocop
      - rspec:
          requires:
            - rubocop